version: '3'

services:
  api:
    build:
        context: ./project-n-backend
        dockerfile: Dockerfile
    volumes:
      - ./project-n-backend:/var/www/html
    ports:
      - '8080:80'
    depends_on:
      - db
  db:
    image: mongo
    environment:
      - MONGO_INITDB_DATABASE=api
      - MONGO_INITDB_ROOT_USERNAME=hterceiro
      - MONGO_INITDB_ROOT_PASSWORD=123456
    ports:
      - "27017:27017"
  web:
    container_name: project-n-frontend
    build:
      context: ./project-n-frontend
      dockerfile: Dockerfile
    volumes:
      - './project-n-frontend:/app'
      - '/app/node_modules'
    ports:
      - '3001:3000'
    environment:
      - CHOKIDAR_USEPOLLING=true
