version: '3'

services:
  api:
    build:
        context: .
        dockerfile: Dockerfile
    volumes:
      - ./:/var/www/html
    ports:
      - '8080:80'
    depends_on:
      - db
  db:
    image: mongo
    environment:
      - MONGO_INITDB_DATABASE=api
      - MONGO_INITDB_ROOT_USERNAME=hterceiro
      - MONGO_INITDB_ROOT_PASSWORD=123456
    ports:
      - "27017:27017"