<?php

namespace Container2j1xJgf;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class get_ServiceLocator_SdwxgZ0Service extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.service_locator.SdwxgZ0' shared service.
     *
     * @return \Symfony\Component\DependencyInjection\ServiceLocator
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['.service_locator.SdwxgZ0'] = new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($container->getService, [
            'profile' => ['services', 'profiler', 'getProfilerService', false],
            'response' => ['privates', '.errored..service_locator.SdwxgZ0.Symfony\\Component\\HttpFoundation\\Response', NULL, 'Cannot autowire service ".service_locator.SdwxgZ0": it references class "Symfony\\Component\\HttpFoundation\\Response" but no such service exists.'],
        ], [
            'profile' => '?',
            'response' => 'Symfony\\Component\\HttpFoundation\\Response',
        ]);
    }
}
