<?php

namespace Container2j1xJgf;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getStatusControllerService extends App_KernelDevDebugContainer
{
    /**
     * Gets the public 'App\Controller\StatusController' shared autowired service.
     *
     * @return \App\Controller\StatusController
     */
    public static function do($container, $lazyLoad = true)
    {
        include_once \dirname(__DIR__, 4).'/src/Controller/StatusController.php';

        return $container->services['App\\Controller\\StatusController'] = new \App\Controller\StatusController();
    }
}
